In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# ONE HOT ENCODING

In [2]:
df=pd.DataFrame({
    "colour" : ["red","blue" , "black" , "green" , "yellow" , "orange"]
})

In [3]:
df

   colour
0     red
1    blue
2   black
3   green
4  yellow
5  orange

In [4]:
OHE_encoder=OneHotEncoder()

In [5]:
OHE_encoded=OHE_encoder.fit_transform(df[["colour"]]).toarray()

In [6]:
OHE_encoded

array([[0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.]])

In [7]:
OHE_encoded_df=pd.DataFrame(OHE_encoded , columns=OHE_encoder.get_feature_names_out())    #Returns the column names created by the encoder
OHE_encoded_df

,colour_black,colour_blue,colour_green,colour_orange,colour_red,colour_yellow
0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0
5,0.0,0.0,0.0,1.0,0.0,0.0

# LABEL ENCODING

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
LE_encoder=LabelEncoder()

In [10]:
LE_encoded=LE_encoder.fit_transform(df[["colour"]])

/home/sidd/miniconda3/envs/ml/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [11]:
LE_encoded

array([4, 1, 0, 2, 5, 3])

In [12]:
# IF we purposefully wanna give our rankes to categories , we use Ordinal Encoding

# ORDINAL ENCODING

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
ranked=pd.DataFrame({
    "size" : ["small","medium" , "small" , "medium" , "large"]
})

In [21]:
OE_encoder=OrdinalEncoder(categories=[["small","medium" , "large"]])

In [22]:
OE_encoded=OE_encoder.fit_transform(ranked[["size"]])

In [23]:
OE_encoded

array([[0.],
       [1.],
       [0.],
       [1.],
       [2.]])

# TARGET GUIDED ORDINAL ENCODING

In [27]:
df = pd.DataFrame({
    'city' : ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]})

In [28]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [31]:
mean_price=df.groupby("city")["price"].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [32]:
df["city_encoded"] = df["city"].map(mean_price)

In [33]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0